# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ff07ae41b2164bfaf687e9c60123b35f1123c79817e4d2d6824efbf4301e27f0dcbd6c3079d853235a3e12af82d5d5e6a40e57a78060ae3b8b5e3254500226bb

test:
  secret_key_base: bcc4ece42360ea3f5790522125991db89171f6bab2986a960677211fc012857772662637101212139800f082347fb3d48bc422f292149d9f27be67730259d8a9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
